doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"
    options:
      1002: 'SET sql_mode=(SELECT REPLACE(@@sql_mode, "ONLY_FULL_GROUP_BY", ""))'

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        dir: "%kernel.project_dir%/src/Entity"
        prefix: 'App\Entity'
        alias: App
    dql:
      datetime_functions:
        MONTH: App\Function\MonthFunction
        YEAR: App\Function\YearFunction
        DAY: App\Function\DayFunction
        DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
